services:
  - type: web
    name: tasktrack-api
    runtime: docker
    plan: free
    dockerfilePath: ./TaskTrack.API/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    initialDeployHook: 'psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f /app/TaskManagementDB_Postgres.sql'
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: tasktrack-db
          property: connectionString
      - key: FrontendUrl
        value: https://asm-1-tasktrack-fe.vercel.app

databases:
  - name: tasktrack-db
    databaseName: tasktrackdb
    user: tasktrack
    plan: free
